### ISSUE TITLE
Esto es normal?

### ISSUE THREAD

**Issue by ghost** [UltiRequiem/UltiVim#4]
![image](https://user-images.githubusercontent.com/70576040/139068113-2b74ee3e-16b8-49a7-92be-6752dbb90bba.png)

Esperé 15 minutos para ver si se pasaba, y aunque en la captura se ven menos de 100 procesos, durante bastante tiempo hubo más de 200

**Comment by UltiRequiem** [comment]
No, lo se, no uso Windows hace tiempo, pero por lo que llego a ver en la screenshot, nvim no es lo que esta causando el problema.

![image](https://user-images.githubusercontent.com/71897736/139068956-8ed791e7-1498-4b72-9eab-3ec21529648e.png)

**Comment by UltiRequiem** [comment]
En mi computadora, NeoVim casi no consume recursos:
![image](https://user-images.githubusercontent.com/71897736/139069319-1e116525-e3dd-436e-9368-0ac3c81161b8.png)

**Comment by ghost** [comment]
Es raro, puse mis configs viejas de nuevo y no pasa eso.
Me pregunto que ocasiona ese error

**Comment by UltiRequiem** [comment]
Si es que necesitas mas ayuda relacionada a la configuracion, vuelve abrir el issue.
